### ISSUE TITLE
are model classes in Hl7.Fhir.Model still generated by the FHIR publication tool?

### ISSUE THREAD

**Issue by jackliusr** [FirelyTeam/firely-docs-firely-net-sdk#68]
According to [Hl7.Fhir.Model contains model classes that correspond to the FHIR Resources and data types, like Patient and HumanName. The code is generated by the FHIR publication tool](https://github.com/FirelyTeam/firely-docs-firely-net-sdk/blob/master/model/introduction.rst#:~:text=Hl7.Fhir.Model%20contains%20model%20classes%20that%20correspond%20to%20the%20FHIR%20Resources%20and%20data%20types%2C%20like%20Patient%20and%20HumanName.%20The%20code%20is%20generated%20by%20the%20FHIR%20publication%20tool%2C),  model classes in Hl7.Fhir.Model  are generated by the FHIR publication tool. I couldn't find any information or links about the tool.  I only found an issue "https://github.com/FirelyTeam/firely-net-sdk/issues/1478" , microsoft/fhir-codgen is mentioned in the issue.  May I know model classes in Hl7.Fhir.Model are generated by the FHIR publication tool?

**Comment by mmsmits** [comment]
Sure! It's not a secret :) We used to generate them using the FHIR Publication tool, but switched the use https://github.com/microsoft/fhir-codegen because it was easier to maintain. We have a fork of this repository which we use to create our classes. 

The generation of the classes is still based on the artifacts from the FHIR specification itself. 

Is there any other question you have about the class generation?

**Comment by jackliusr** [comment]
@mmsmits, Thank you, your response clarifies my doubt. I don't have others.
